---
after_install:
  - cp $HOME/xdebug.ini $HOME/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini || return 0
after_script:
  - "php vendor/bin/coveralls"
before_install:
  - mv $HOME/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini $HOME/xdebug.ini || return 0
  - "travis_retry composer global require hirak/prestissimo"
before_script:
  - "mkdir -p build/logs"
cache:
  directories:
    - $HOME/.composer/cache
env:
  matrix:
    - DEPENDENCIES="high"
    - DEPENDENCIES="low"
install:
  - "if [[ \"$DEPENDENCIES\" = 'high' ]]; then travis_retry composer update --no-interaction --no-ansi --no-progress --no-suggest --optimize-autoloader --prefer-stable; fi"
  - "if [[ \"$DEPENDENCIES\" = 'low' ]]; then travis_retry composer update --no-interaction --no-ansi --no-progress --no-suggest --optimize-autoloader --prefer-stable --prefer-lowest; fi"
language: php
php:
  - 7.0
  - 7.0snapshot
  - 7.1
  - 7.1snapshot
script:
  - "./vendor/bin/grumphp run"
sudo: false
